# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{downlow}
  s.version = "0.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aaron Quint"]
  s.date = %q{2011-07-01}
  s.description = %q{Downlow provides an easy way to fetch files or archives and extract them with minimal hassle.}
  s.email = %q{aaron@quirkey.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "downlow.gemspec",
    "lib/downlow.rb",
    "lib/downlow/ext/pathname.rb",
    "lib/downlow/extractor.rb",
    "lib/downlow/extractors/dir.rb",
    "lib/downlow/extractors/tar_gz.rb",
    "lib/downlow/extractors/zip.rb",
    "lib/downlow/fetcher.rb",
    "lib/downlow/fetchers/git.rb",
    "lib/downlow/fetchers/github.rb",
    "lib/downlow/fetchers/http.rb",
    "lib/downlow/fetchers/local.rb",
    "test/fixtures/gist_response",
    "test/fixtures/location_response",
    "test/fixtures/test.tar.gz",
    "test/fixtures/test.zip",
    "test/helper.rb",
    "test/test_downlow.rb",
    "test/test_downlow_extractor.rb",
    "test/test_downlow_fetcher.rb"
  ]
  s.homepage = %q{http://github.com/quirkey/downlow}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{easy downloading and extracting API}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rubyzip>, [">= 0.9.4"])
      s.add_runtime_dependency(%q<archive-tar-minitar>, [">= 0.5.2"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<fakeweb>, [">= 1.2"])
    else
      s.add_dependency(%q<rubyzip>, [">= 0.9.4"])
      s.add_dependency(%q<archive-tar-minitar>, [">= 0.5.2"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<fakeweb>, [">= 1.2"])
    end
  else
    s.add_dependency(%q<rubyzip>, [">= 0.9.4"])
    s.add_dependency(%q<archive-tar-minitar>, [">= 0.5.2"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<fakeweb>, [">= 1.2"])
  end
end

